language: ruby
rvm:
  - 2.4.1

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

script: 
  - bundle install
  - bundle exec rake preview

after_success:
  - bundle gen_deploy

