markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Y丫Y
host: icai.github.com




meta:
    author:
        name: icai
        email: gidcai@gmail.com
        disqus: gidcai                               # Disqus缩略标识
        gcse: 001585136437331322683:wvcrg0yva3i    # Google自定义搜索标识ID
        github: icai                                 # GitHub账号
        gravatar: 750a24b137f6f1f3313127daf9c9152d   # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: https://secure.gravatar.com/avatar/        # Gravatar头像服务器地址


custom:
    category:
        thinking: 思考随笔
        problems: 问题记录
        knowledge: 知识经验
        opencode: 开源项目
    categories:
      - name:  thinking
        title: 思考随笔

      - name:  problems
        title: 问题记录

      - name:  knowledge
        title: 知识经验

      - name:  opencode
        title: 开源项目



